"use client";
import Image from 'next/image'; import { useMemo, useState } from 'react'; import { artworkFilters, artworks } from '@/content/artworks'; import { discordUrl, instagramUrl, xUrl } from '@/content/socials'; import { SectionShell } from './SectionShell'; import { ArtworkLightbox } from './ArtworkLightbox';
export function ArtworkGallery(){ const [filter,setFilter]=useState<(typeof artworkFilters)[number]>('All'); const filtered=useMemo(()=>artworks.filter(a=>filter==='All'||a.tags.includes(filter)),[filter]); const [light,setLight]=useState<number|null>(null); const featured=artworks.filter(a=>a.featured); const spotlight=featured[0]||artworks[0]; const support=artworks.filter(a=>a.id!==spotlight.id).slice(0,3);
 return <SectionShell id="artworks" eyebrow="Selected portfolio" title="Artworks that sell the commission" intro="Real Carrd artwork assets are shown with their actual dimensions, natural aspect ratios, responsive masonry, and a high-res lightbox.">
  <div className="grid gap-4 lg:grid-cols-[1.4fr_.9fr]"><button onClick={()=>setLight(artworks.findIndex(a=>a.id===spotlight.id))} className="group relative overflow-hidden rounded-[2rem] border border-white/15 bg-white/5 text-left shadow-glow"><Image src={spotlight.src} alt={spotlight.alt} width={spotlight.width} height={spotlight.height} priority sizes="(max-width:1024px) 100vw, 58vw" className="h-auto w-full"/><div className="absolute inset-x-4 bottom-4 rounded-3xl border border-white/15 bg-ink/70 p-4 backdrop-blur-xl"><p className="eyebrow">Featured artwork</p><h3 className="font-display text-3xl">{spotlight.title}</h3><p className="text-sm text-cream/70">{spotlight.tags.join(' • ')}</p></div></button><div className="grid gap-4 sm:grid-cols-3 lg:grid-cols-1">{support.map(a=><button key={a.id} onClick={()=>setLight(artworks.findIndex(x=>x.id===a.id))} className="group overflow-hidden rounded-[1.6rem] border border-white/15 bg-white/5 text-left"><Image src={a.src} alt={a.alt} width={a.width} height={a.height} sizes="(max-width:1024px) 33vw, 30vw" className="h-auto w-full transition group-hover:scale-[1.025]"/><div className="p-3 text-sm font-bold text-cream/70">{a.title}</div></button>)}</div></div>
  <div className="sticky top-24 z-10 -mx-1 mt-8 flex gap-2 overflow-x-auto px-1 pb-3 no-scrollbar">{artworkFilters.map(f=><button key={f} onClick={()=>setFilter(f)} className={`shrink-0 rounded-full border px-4 py-2 text-sm font-black transition ${filter===f?'border-lavender bg-lavender text-ink':'border-white/12 bg-ink/60 text-cream/70 hover:text-cream'}`}>{f} <span className="opacity-60">{f==='All'?artworks.length:artworks.filter(a=>a.tags.includes(f)).length}</span></button>)}</div>
  <div className="gallery-masonry mt-4">{filtered.map(a=><button key={a.id} onClick={()=>setLight(artworks.findIndex(x=>x.id===a.id))} className="gallery-card group relative border border-white/12 bg-white/[.045] text-left shadow-atelier"><Image src={a.src} alt={a.alt} width={a.width} height={a.height} sizes="(max-width:640px) 100vw, (max-width:1024px) 50vw, (max-width:1536px) 33vw, 25vw" className="h-auto w-full object-contain" loading={a.featured?'eager':'lazy'}/><div className="p-4 md:absolute md:inset-x-3 md:bottom-3 md:translate-y-2 md:rounded-2xl md:border md:border-white/12 md:bg-ink/72 md:opacity-0 md:backdrop-blur-xl md:transition group-hover:translate-y-0 group-hover:opacity-100"><b>{a.title}</b><p className="mt-1 text-xs text-cream/65">☾ {a.tags.join(' • ')} • {a.width}×{a.height}</p></div></button>)}</div>
  {filtered.length===0&&<div className="card p-6 text-cream/70">No artworks in this filter yet. More can be added later in <code>src/content/artworks.ts</code>.</div>}
  <div className="mt-8 flex flex-wrap gap-3"><a className="btn btn-primary" href={instagramUrl} target="_blank" rel="noreferrer">See more artworks on Instagram</a><a className="btn btn-ghost" href={xUrl} target="_blank" rel="noreferrer">Follow updates on X</a><a className="btn btn-ghost" href={discordUrl} target="_blank" rel="noreferrer">Join the Discord</a></div>
  {light!==null&&<ArtworkLightbox items={artworks} index={light} onClose={()=>setLight(null)} onMove={setLight}/>} </SectionShell> }
