import Image from 'next/image';
import type { SocialArtwork } from '@/content/artworks';
import { sourceLabel } from '@/content/artworks';
const chapterMeta = [
  ['01 / Signature Mood','Soft anime portraits with a dreamy emotional tone.','A featured social artwork that best represents Rinnozuki’s moody anime commission style.'],
  ['02 / Cute Chibi Energy','Small proportions, strong charm, and playful expression.','A curated chibi-focused artwork from the social art feed.'],
  ['03 / Mascot & Character Presence','Character designs that feel readable and commission-ready.','A piece that sells mascot / VTuber / OC presentation.'],
  ['04 / Scene & Story','Illustrations that feel like a small memory.','Environment, lighting, and atmosphere for cover or gift-style artwork.'],
  ['05 / Sticker / Utility','Expressions designed to be used everywhere.','Cute branding value for chat, community, and emote-style work.'],
];
export function ArtworkStory({items,onSelect}:{items:SocialArtwork[];onSelect:(id:string)=>void}){ const chapters=[items.find(i=>i.id.includes('206479')),items.find(i=>i.tags.includes('Chibi')),items.find(i=>i.tags.includes('Mascot / Vtuber')),items.find(i=>i.id.includes('202409'))||items.find(i=>i.id.includes('196204')),items.find(i=>i.id.includes('198489'))].filter(Boolean) as SocialArtwork[];
 return <div className="mt-8"><div className="hidden lg:block"><div className="grid gap-6 lg:grid-cols-[.85fr_1.15fr]"><div className="sticky top-28 h-[72vh] rounded-[2rem] border border-white/12 bg-white/[.045] p-6 shadow-glow"><p className="eyebrow">Cinematic story</p><h3 className="mt-2 font-display text-5xl leading-none">From social post to commission dream.</h3><p className="mt-5 leading-7 text-cream/66">Curated art posts from X are arranged as a story board. Carrd sheets remain only as fallback/reference.</p><div className="mt-8 space-y-3">{chapterMeta.map(([k,t],i)=><div key={k} className="rounded-3xl border border-white/10 bg-white/5 p-3"><p className="text-xs font-black text-blush">{k}</p><p className="font-bold">{t}</p></div>)}</div></div><div className="space-y-10">{chapters.map((item,i)=><article key={item.id} className="min-h-[72vh] rounded-[2.2rem] border border-white/12 bg-gradient-to-br from-white/[.09] to-white/[.035] p-4 shadow-atelier"><button onClick={()=>onSelect(item.id)} className="grid h-full w-full gap-5 text-left xl:grid-cols-[1.1fr_.9fr]"><div className="flex items-center justify-center rounded-[1.7rem] bg-ink/45 p-3"><Image src={item.imageUrl} alt={item.title} width={item.width} height={item.height} sizes="(max-width:1280px) 55vw, 42vw" className="max-h-[64vh] w-auto rounded-[1.4rem] object-contain" priority={i<2}/></div><div className="flex flex-col justify-center p-4"><p className="eyebrow">{chapterMeta[i]?.[0]}</p><h3 className="mt-2 font-display text-5xl leading-none">{chapterMeta[i]?.[1] || item.title}</h3><p className="mt-5 leading-7 text-cream/68">{chapterMeta[i]?.[2] || item.description}</p><div className="mt-5 flex flex-wrap gap-2">{item.tags.map(t=><span className="rounded-full border border-white/10 bg-white/5 px-3 py-1 text-xs font-bold" key={t}>{t}</span>)}</div><p className="mt-5 text-sm font-black text-lavender">{sourceLabel(item.source)} • open full artwork →</p></div></button></article>)}</div></div></div>
 <div className="grid gap-4 lg:hidden">{chapters.map((item,i)=><button key={item.id} onClick={()=>onSelect(item.id)} className="card overflow-hidden text-left"><Image src={item.imageUrl} alt={item.title} width={item.width} height={item.height} className="h-auto w-full"/><div className="p-5"><p className="eyebrow">{chapterMeta[i]?.[0]}</p><h3 className="font-display text-3xl">{chapterMeta[i]?.[1]}</h3><p className="mt-2 text-cream/65">{item.title}</p></div></button>)}</div></div> }
