"use client";
import { useMemo, useState } from 'react'; import { discordUrl, instagramUrl, xUrl } from '@/content/socials'; import { SectionShell } from './SectionShell';
type Lang='en'|'id'; type Values=Record<string,string>;
const initial:Values={ name:'', email:'', contactPlatform:'Instagram', contactHandle:'', paymentMethod:'Mandiri', commissionStyle:'Chibi', type:'Headshot', characterCount:'1', usage:'Personal', deadline:'Flexible', vibe:'', description:'', lore:'', design:'', references:'', notes:'', tos:'' };
const copy={ en:{contact:'Contact',details:'Commission Details',story:'References & Story',review:'Review & Submit',name:'Name / social handle',email:'Email',preferred:'Preferred contact',handle:'Contact username/link',payment:'Payment method',style:'Commission style',type:'Type',chars:'Number of characters',usage:'Usage',deadline:'Deadline',vibe:'Desired vibe / mood',description:'Description',lore:'Personality / lore / story',design:'Design enhancements / accessories',refs:'Reference links',notes:'Additional note',agree:'I have read and agree to RinnOZ Terms of Service.',submit:'Submit Order',copy:'Copy Order Summary',manual:'Email Manually'}, id:{contact:'Kontak',details:'Detail Komisi',story:'Referensi & Cerita',review:'Review & Kirim',name:'Nama / nama akun media sosial',email:'Email',preferred:'Kontak utama',handle:'Username/link kontak',payment:'Pembayaran melalui',style:'Jenis komisi',type:'Tipe',chars:'Jumlah karakter',usage:'Penggunaan',deadline:'Deadline',vibe:'Vibe / mood yang diinginkan',description:'Deskripsi',lore:'Kepribadian / lore / cerita',design:'Tambahan desain / aksesoris',refs:'Link referensi',notes:'Catatan tambahan',agree:'Saya sudah membaca dan menyetujui Terms of Service RinnOZ.',submit:'Kirim Order',copy:'Salin Ringkasan',manual:'Email Manual'} };
function Field({label,children,help}:{label:string;children:React.ReactNode;help?:string}){return <label className="space-y-2"><span>{label}</span>{children}{help&&<small className="helper block">{help}</small>}</label>}
function buildSummary(v:Values, lang:Lang){ return `RinnOZ Commission Order
Submitted: ${new Date().toLocaleString()}
Source: ${typeof location!=='undefined'?location.href:'website'}
Language: ${lang.toUpperCase()}

CLIENT
Name / handle: ${v.name}
Email: ${v.email}
Preferred contact: ${v.contactPlatform}
Contact username/link: ${v.contactHandle}

COMMISSION
Style: ${v.commissionStyle}
Type: ${v.type}
Characters: ${v.characterCount}
Usage: ${v.usage}
Deadline: ${v.deadline}
Vibe / mood: ${v.vibe}
Payment method: ${v.paymentMethod}

DETAILS
Description: ${v.description}
Personality / lore / story: ${v.lore}
Design enhancements / accessories: ${v.design}
References: ${v.references}
Additional notes: ${v.notes}

TERMS
Client agreed to RinnOZ Terms of Service: ${v.tos?'yes':'no'}`; }
export function OrderWizard(){ const [lang,setLang]=useState<Lang>('en'); const [step,setStep]=useState(0); const [values,setValues]=useState<Values>(initial); const [status,setStatus]=useState(''); const [mailto,setMailto]=useState(''); const t=copy[lang]; const steps=[t.contact,t.details,t.story,t.review]; const summary=useMemo(()=>buildSummary(values,lang),[values,lang]); function set(k:string,val:string){setValues(v=>({...v,[k]:val}))} function input(k:string){return {name:k,value:values[k]||'',onChange:(e:React.ChangeEvent<HTMLInputElement|HTMLTextAreaElement|HTMLSelectElement>)=>set(k,e.target.value)}}
 async function submit(){ setStatus('Sending order...'); setMailto(''); const payload={...values, language:lang, source:location.href}; try{ const r=await fetch('/api/order',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}); const j=await r.json(); setStatus(j.ok?'Order sent successfully. Keep a copy of your summary too.':`Failed: ${j.error}`); if(j.mailto) setMailto(j.mailto); }catch(e){ setStatus('Failed to send. Please copy the summary or use manual email.'); setMailto(`mailto:takayuki.rinnozuki@gmail.com?subject=${encodeURIComponent(`[RinnOZ Commission] New order from ${values.name} — ${values.commissionStyle}/${values.type}`)}&body=${encodeURIComponent(summary)}`); }}
 const canNext = step<3; return <SectionShell id="order" eyebrow="Commission request" title="Order wizard" intro="A guided bilingual form that creates a clean summary and sends your request to takayuki.rinnozuki@gmail.com."><div className="card p-5 md:p-8"><div className="mb-6 flex flex-wrap items-center justify-between gap-3"><div className="flex gap-2">{steps.map((s,i)=><button key={s} onClick={()=>setStep(i)} className="flex items-center gap-2 rounded-full border border-white/10 bg-white/5 px-3 py-2 text-sm font-black"><span className={`step-dot ${i===step?'active':''}`}>{i+1}</span><span className="hidden sm:inline">{s}</span></button>)}</div><div className="flex rounded-full border border-white/10 bg-white/5 p-1"><button className={`rounded-full px-4 py-2 font-black ${lang==='en'?'bg-lavender text-ink':''}`} onClick={()=>setLang('en')}>EN</button><button className={`rounded-full px-4 py-2 font-black ${lang==='id'?'bg-lavender text-ink':''}`} onClick={()=>setLang('id')}>ID</button></div></div>
 <input name="website" value="" readOnly className="hidden" aria-hidden="true" />
 {step===0&&<div className="grid gap-4 md:grid-cols-2"><Field label={t.name}><input required {...input('name')}/></Field><Field label={t.email}><input required type="email" {...input('email')}/></Field><Field label={t.preferred}><select {...input('contactPlatform')}><option>Instagram</option><option>X</option><option>Discord</option><option>Email</option><option>Other</option></select></Field><Field label={t.handle}><input {...input('contactHandle')}/></Field></div>}
 {step===1&&<div className="grid gap-4 md:grid-cols-2"><Field label={t.payment}><select {...input('paymentMethod')}><option>Mandiri</option><option>Dana</option><option>PayPal</option></select></Field><Field label={t.style}><select {...input('commissionStyle')}><option>Chibi</option><option>Anime</option><option>Other</option><option>Discuss first</option></select></Field><Field label={t.type}><select {...input('type')}><option>Headshot</option><option>Bust Up</option><option>Half Body</option><option>Full Body</option><option>Emote</option><option>Character Sheet</option><option>Other</option></select></Field><Field label={t.chars}><input type="number" min="1" {...input('characterCount')}/></Field><Field label={t.usage}><select {...input('usage')}><option>Personal</option><option>Commercial discussion needed</option></select></Field><Field label={t.deadline}><select {...input('deadline')}><option>Flexible</option><option>Specific date</option><option>Rush</option></select></Field><Field label={t.vibe}><input {...input('vibe')}/></Field></div>}
 {step===2&&<div className="grid gap-4 md:grid-cols-2"><Field label={t.description}><textarea required {...input('description')}/></Field><Field label={t.lore}><textarea {...input('lore')}/></Field><Field label={t.design}><textarea {...input('design')}/></Field><Field label={t.refs} help="Google Drive, Imgur, Toyhouse, Pinterest board, direct image links, or DM references."><textarea required {...input('references')}/></Field><Field label={t.notes}><textarea {...input('notes')}/></Field></div>}
 {step===3&&<div className="grid gap-5 lg:grid-cols-[1fr_.9fr]"><div><pre className="max-h-[520px] whitespace-pre-wrap rounded-3xl border border-white/10 bg-ink/55 p-5 text-sm leading-6 text-cream/78">{summary}</pre></div><div className="space-y-4"><label className="flex items-start gap-3 rounded-3xl border border-white/10 bg-white/5 p-4 text-cream/80"><input className="mt-1 w-auto" type="checkbox" checked={values.tos==='yes'} onChange={e=>set('tos',e.target.checked?'yes':'')}/><span>{t.agree}</span></label><button className="btn btn-primary w-full" onClick={submit}>{t.submit}</button><button className="btn btn-ghost w-full" onClick={()=>navigator.clipboard.writeText(summary)}>{t.copy}</button><a className="btn btn-ghost w-full" href={mailto||`mailto:takayuki.rinnozuki@gmail.com?subject=${encodeURIComponent(`[RinnOZ Commission] New order from ${values.name} — ${values.commissionStyle}/${values.type}`)}&body=${encodeURIComponent(summary)}`}>{t.manual}</a><div className="grid gap-2 sm:grid-cols-3"><a className="btn btn-ghost" href={instagramUrl} target="_blank" rel="noreferrer">Instagram</a><a className="btn btn-ghost" href={discordUrl} target="_blank" rel="noreferrer">Discord</a><a className="btn btn-ghost" href={xUrl} target="_blank" rel="noreferrer">X</a></div>{status&&<p className="rounded-3xl border border-white/10 bg-white/5 p-4 text-cream/75">{status}</p>}</div></div>}
 <div className="mt-7 flex justify-between gap-3"><button className="btn btn-ghost" disabled={step===0} onClick={()=>setStep(s=>Math.max(0,s-1))}>← Back</button>{canNext&&<button className="btn btn-primary" onClick={()=>setStep(s=>Math.min(3,s+1))}>Next →</button>}</div></div></SectionShell> }
